language: node_js
node_js:
  - '0.10'
cache:
  bundler: true
  directories:
    - node_modules
env:
  - NODE_ENV=test
notifications:
  webhooks: 'https://deploy-state.octoblu.com/deployments/travis-ci/org'
